# Generated by Django 5.2.17 on 2026-09-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='activity',
            field=models.CharField(choices=[('DINNER', 'Dinner'), ('EVENT', 'Event'), ('WALK', 'Walk'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
